version: '3.8'
services:
  app:
    build: .
    restart: always
    command: gunicorn run:app -b :5000
    environment:
      - MONGO_USERNAME=${DB_USER}
      - MONGO_PASSWORD=${DB_PASS}
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: mongo:latest
    restart: always
    hostname: review_mongo
    environment:
      - MONGO_INITDB_DATABASE=review_db
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017
volumes:
  dbdata:
