REVIEWERS = [
    'Karen Osborn',
    'Mary Wicksten',
    'Enrique Macpherson',
    'Keiji Baba',
    'Bob Van Syoc',
    'Buz Wilson',
    'Tom Hansknecht',
    'Marina Malyutina',
    'Chris Boyko',
    'Scott France',
    'Les Watling',
    'Tina Molodtsova',
    'Steven Cairns',
    'Dennis Opresko',
    'Asako Matsumoto',
    'Nadya Sanamyan',
    'Daniel Wagner',
    'Amy Baco-Taylor',
    'Allen Collins',
    'Phil Alderslade',
    'Estefania Rodriguez',
    'Abby LaPointe',
    'Christopher Mah',
    'Andrey Gebruk',
    'Antonina Rogacheva',
    'Charles Messing',
    'Richard Mooi',
    'David Pawson',
    'Alexander Mironov',
    'Doug Eernisse',
    'Marc Eleaume',
    'Michel Roux',
    'Tim O\'Hara',
    'Karen Sanamyan',
    'Pamela Neubert',
    'Kevin Kocot',
    'Jessica Goodheart',
    'Terry Gosliner',
    'Julia Sigwart',
    'Robert Moffitt',
    'Claudia Mills',
    'Erik V. Thuesen',
    'Steven Haddock',
    'Matthew R. L. Jones',
    'Michael Vecchione',
    'George Matsumoto',
    'Carole Hickman',
    'Meagan McCuller',
    'Harlan K. Dean',
    'Konstantin Tabachnick',
    'Henry Reiswig',
    'Rob van Soest',
    'Christopher Kelley',
    'Javier Murillo-Perez',
    'Shirley Pomponi',
    'Bruce Mundy',
    'Kenneth Sulak',
    'Jorgen Nielsen',
    'Tomio Iwamoto',
    'John McCosker',
    'Andrea Quattrini',
    'Dominique Didier',
    'David Ebert',
    'Mackenzie Gerringer',
    'Astrid Leitner',
    'Jeff Drazen',
    'Peter Møller',
    'Werner Schwarzhans',
    'David Smith',
    'Hsuan Ching Ho',
    'Hiroyuki Motomura',
    'Kyoji Fujiwara',
    'Yoshiaki Kai',
    'Nozomu Muto'
]